### ISSUE TITLE
Update pipelines to GH Actions

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/TestTools#116]

**Comment by PandaMagnus** [comment]
@Keboo I need to get some updates buttoned up for Selenate and TestFramework. I'll try to do this when I do those.

**Comment by BenjaminMichaelis** [comment]
Updated pipeline to GH Actions on https://github.com/IntelliTect/TestTools.Console after migrating it out to its own repository.

**Comment by BenjaminMichaelis** [comment]
> @Keboo I need to get some updates buttoned up for Selenate and TestFramework. I'll try to do this when I do those.

We should be able to use a similar pipeline as TestTools.Console uses after this pr is merged and we separate it into it's own repo

**Comment by BenjaminMichaelis** [comment]
Closing this for now, I assume as we accomplish #122, we will update pipelines to GH actions as well
