### ISSUE TITLE
Change description to reflect repo is a collection of tools

### ISSUE THREAD

**Issue by PandaMagnus** [IntelliTect/TestTools#18]
Current description is: "Simple end-to-end test framework for .NET console applications". This should be changed to something like, "A collection of tools for aiding in test automation".

**Comment by Keboo** [comment]
No objection from me

**Comment by PandaMagnus** [comment]
I do not appear to have rights to do this. Or I'm missing how to do it. :)

**Comment by Keboo** [comment]
Done
