### ISSUE TITLE
MVP for TestRunner v2

### ISSUE THREAD

**Issue by PandaMagnus** [IntelliTect/TestTools#36]
Add MVP for TestRunner v2 to TestTools. Basically, figure out and implement...

1) Does it make sense to still use DI
   a) If not, what's another good way to structure both test inputs/outputs and discrete application functions (i.e. "test blocks")
   b) If so, does it make sense to switch to Microsoft.Extensions.DependencyInjection?
2) "Automatic logging" needs to happen
3) Logging can be easily switchable (Database, native test framework, standard output, etc.)
4) Scheduling test runs? Might be too tool specific
5) ???

**Comment by PandaMagnus** [comment]
After tinkering around, DI still seems like the best option for an easy way to get logging and some measure of setup "for free". However, to alleviate the issues we see passing data around, we should add an AddParameter, AddArgument or AddData so we can add/change objects in the container on the fly.

Two big benefits: using something like a string becomes feasible, and we can change objects for specific test blocks.

Should it take a collection of some sort, or force one object per call? Support both?

**Comment by GrantErickson** [comment]
That sounds like a good idea. Let’s chat tomorrow and discuss details.

**Comment by Keboo** [comment]
I would be curious to understand the goals. DI is awesome and powerful, but typically the wrong tool for holding onto state. If you go the DI route, I would highly suggest using the MS abstraction library to avoid tying your code to any single DI container, this however adds complexity as you are using an abstraction library over a DI container which itself is an abstraction for dependencies.

**Comment by PandaMagnus** [comment]
Well, I'm kinda using "DI" in a loaded way right now. There's two things going on:
1) a quick and easy way to build automated test cases that get you some stuff "for free" so a team doesn't have to rely on everyone being diligent with explicit log calls. This probably doesn't classify as _actual_ dependency injection, since all we're really doing here is just telling some service which classes need to be instantiated at runtime to use in our test.
2) We need someway to pass "things" into the above mentioned classes and a test method in said classes without necessarily relying on the tester knowing the application under test's data well enough to do potential data transforms. So E.G. one of our use cases is someone like Yuriy or I write a factory or a constructor for fetching CCB data. All anyone on the team needs to know is "I need an account", so they ask a service or container for an account, and we've made all the magic behind the scenes happen to make it work when an account is asked for.

If you're in the office tomorrow, I can walk over on lunch or something to chat more. I've been trying to come up with ways around abstracting some of this away from the test author as it gets difficult to manage if someone deviates from a known, workable pattern.

**Comment by Keboo** [comment]
Yea I will be around. Swing by anytime.

**Comment by PandaMagnus** [comment]
Lost track of time today. :( Here are the three different options I've been toying around with to get what we want (alternatively take a look at TestRunnerV2 branch)...

TestBlocksExample testing = new TestBlocksExample();
            // Option 1. This is pretty typical, we new up an instance of the class adn use it
            bool r1 = testing.TestBlock1();
            testing.TestBlock2(false, r1);

            // Option 2. This allows us to wrap the delegate calls with standard logging, but getting the return value is a bit weird.
            // QUESTION: Do out parameters work when invoking the function as a delegate? That might be a better option.
            TestBuilder builder = new TestBuilder();
            builder.AddTestBlock(
                () => { r1 = testing.TestBlock1(); },
                () => { testing.TestBlock2(false, r1); }
            ).ExecuteTest();
            // OR... same as above but not using a params Action[] parameter
            builder
                .AddTestBlock(() => { r1 = testing.TestBlock1(); })
                .AddTestBlock(() => { testing.TestBlock2(false, r1); })
                .ExecuteTest();


            // Option 3 is by type. That avoids needing to explicitely new up an instance of a class, and makes the calls very concise.
            // But it ends up being problematic for passing data into it without some sort of data or DI service. Hence the AddData function.
            builder
                .AddTestBlock<TestBlocks.TestBlock1>()
                .AddData(new TestBlock2ExpectedValues { ExpectedResult = true }, new TestBlock2ActualValues { ActualResult = false })
                .AddTestBlock<TestBlocks.TestBlock2>()
                .ExecuteTest();

**Comment by Keboo** [comment]
Interesting. It looks like you are trying to do something similar to what we did in System.CommandLine with the command handlers. We allow you to pass in an arbitrary delegate, and we magically bind up and pass in the desired parameters based upon the name and the type. 

Though with all of this, it does sort of beg the question. If you want this level of control over the tests, have you considered simply extending [the VSTest stuff](https://github.com/microsoft/vstest/) to get this behavior. That way people don't need to learn a new API or classes. They can continue to use the existing framework and just include your extension.

**Comment by PandaMagnus** [comment]
I've been going back and forth on extending an existing framework, but I'm struggling with  not wanting to tie people to a particular one. So E.G. if they want to use NUnit or XUnit, then they can. However, it might not be worth the trouble to build some additional thing that works within those. I dunno... but it keeps me up at night sometimes. :)

**Comment by PandaMagnus** [comment]
Further research is leaning against Microsoft.Extensions.DependencyInjection. it doesn't natively support property injection, and one of our big use cases is that our test blocks ask for things via constructor arguments and properties. Looking into AutoFac and PocketContainer.

**Comment by Keboo** [comment]
It may still be worth coding against `Microsoft.Extensions.DependencyInjection.Abstractions` though. It will give you a common API, and then you can back with with AutoFac (or pretty much any reasonable DI container). The other thing to sort out is registration (ie. how are you going to configure your container).

**Comment by Keboo** [comment]
@PandaMagnus I may be building in straight library support for AutoDI soon. Another project is going to need it. I am not sure if that would be an option for this or not, but I would love to understand the requirements better just to make sure I cover those as well. 

https://github.com/Keboo/AutoDI/issues/154

**Comment by PandaMagnus** [comment]
I bailed halfway through the day due to a growing cold. If I can get a handle on it tonight, I'll pop over to the office tomorrow to discuss tomorrow morning. Otherwise, it will be later in the week.

**Comment by PandaMagnus** [comment]
@kamonson Want to take a stab at using the available NuGet package to see if this meets the bare minimum amount of "stuff" we've talked about?

**Comment by PandaMagnus** [comment]
Calling this complete. We're using this at a couple of clients now, one of which is being actively maintained. More specific issues have already been created to address more specific changes.
