### ISSUE TITLE
Fix failing ReturnToHomepage test in GoogleSearch ExampleTests

### ISSUE THREAD

**Issue by philspokas** [IntelliTect/TestTools#55]
ReturnToHomepage() is failing with a timeout while waiting an element on the Google Search home page. 

The test steps appear to be correctly executed and the Google Search home page is displayed.

**Comment by PandaMagnus** [comment]
@philspokas Got it. There are two elements on screen with the same html name. It just so happens that the on the first search, the correct button is grabbed first. For whatever reason, when the test returns to the home page, the other (hidden) button is now higher in the DOM. I should have a fix shortly.
