### ISSUE TITLE
Convert to using System.Text.Json instead of Newtonsoft

### ISSUE THREAD

**Issue by PandaMagnus** [IntelliTect/TestTools#62]

**Comment by qtuu** [comment]
i would like to take a stab at this.

**Comment by PandaMagnus** [comment]
Started using this at a client site today. Had to re-wrap the serialization in a try/catch for a quick-fix (long story short, at this client I have to hand a HttpClient around, which understandably does not get converted to JSON well :) .) Not sure if that's the right answer long-term, but I think for the purposes of this specific issue we can close this and address any other changes in a future issue.
